---
- name: Deploy Nginx Container
  hosts: web
  become: yes
  tasks:
    - name: Pull and Start Nginx Container
      community.docker.docker_container:
        name: my-web-site
        image: nginx:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
